### ISSUE TITLE
Youtube link not working on https url

### ISSUE THREAD

**Issue by development-codeface** [kasp3r/link-preview#15] opened 2018-11-06 06:15 UTC
Youtube iframe not loading on https URL.

**Comment by kasp3r** [comment] 2018-11-06 08:10
This library has nothing to do with iframes. Please provide an example how to reproduce a problem.

**Comment by kasp3r** [comment] 2018-11-12 09:28
Closing, because of no answer from OP

**Closed as completed by kasp3r** 2018-11-12 09:28 UTC
